apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child
spec:
  project: default
  destination:
    namespace: argo
    name: test
  sources:
    - path: child/
      repoURL: https://github.com/Cloud-Hacks/sample-argo.git
      targetRevision: test
      helm:
        releaseName: child-app
        parameters:
          - name: image.tag
            value: "latest"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
